[package]
name = "nimbleparse"
description = "Simple Yacc grammar debugging tool"
repository = "https://github.com/softdevteam/grmtools"
version = "0.11.1"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["parsing"]

[[bin]]
doc = false
name = "nimbleparse"

[dependencies]
cfgrammar = { path="../cfgrammar", version="0.11" }
getopts = "0.2"
lrlex = { path="../lrlex", version="0.11" }
lrpar = { path="../lrpar", version="0.11" }
lrtable = { path="../lrtable", version="0.11" }
num-traits = "0.2"
